dist: trusty
sudo: required
language: node_js
node_js:
- 8
cache: npm
before_install:
- sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
before_script:
- npm run lint
- npm run build
deploy:
- provider: npm
  skip_cleanup: true
  email: info@liquality.io
  api_key:
    secure: NcFogb0hRLdqRfC0QwBVYf9WF5JQgSXDTFbBHrG1B413Iqd8f4zqDqZEKcB+rIfi+s4IDOUGxa7fsd/HF3iojy+ruEmic0fzUSRqNdE4SHa0DrNLU5apmMmX8syoDYW55RMqCssKA3Hc9HS3pKbzLYt5ZAQlkc+1HvCpmmluSfMYK3/DUTR2TNX4/b6XiBxZaYfz+wGA3fH+LOBlLOpWo/xcgIOImlZUf5opsFrftdsJ2epiK3vUTcy1+lV9MpUPlrFg27/Ybll0akfQ5kQ5Ac3XhLuKWvqgJCkRsKbWXbBBjTNsrlbWrcTicoR3RPtMD9seNNVW5vWr4GoChefX984fD4t9jSXZyEj/pJIO0Y5PGvUDhM348IvtX+ItCSs/VLuEh9Y+iMd898TPCbawrF1KwNOb7Q5czdOw9uBQb35IqaRdfysVbCGf1ZCzd4h703uKeGsGH+dtzB0XbY88Bvtz0gBMrOfOyEnTxVa2T6eZ0oPQ5n+hFtw3QoXdRBoXvK2K+Qt1Ch7UDjo1JqHGN9ieHaWTUX+6ypWeYi8LcVknok9McVqGhdZAKHHwPL+98atEsn1Op+GQvxLyJ4c47RA6FXhKPBkHLZh5irg7QndVWKmwpgzFSS72GPtF+5xmpD+KPVFQ8meSu0qW2hf7UhW1oQsAIKxcjKoTfjWSYoI=
  on:
    tags: true
    repo: liquality/chainabstractionlayer
    branch: master
- provider: npm
  skip_cleanup: true
  email: info@liquality.io
  api_key:
    secure: NcFogb0hRLdqRfC0QwBVYf9WF5JQgSXDTFbBHrG1B413Iqd8f4zqDqZEKcB+rIfi+s4IDOUGxa7fsd/HF3iojy+ruEmic0fzUSRqNdE4SHa0DrNLU5apmMmX8syoDYW55RMqCssKA3Hc9HS3pKbzLYt5ZAQlkc+1HvCpmmluSfMYK3/DUTR2TNX4/b6XiBxZaYfz+wGA3fH+LOBlLOpWo/xcgIOImlZUf5opsFrftdsJ2epiK3vUTcy1+lV9MpUPlrFg27/Ybll0akfQ5kQ5Ac3XhLuKWvqgJCkRsKbWXbBBjTNsrlbWrcTicoR3RPtMD9seNNVW5vWr4GoChefX984fD4t9jSXZyEj/pJIO0Y5PGvUDhM348IvtX+ItCSs/VLuEh9Y+iMd898TPCbawrF1KwNOb7Q5czdOw9uBQb35IqaRdfysVbCGf1ZCzd4h703uKeGsGH+dtzB0XbY88Bvtz0gBMrOfOyEnTxVa2T6eZ0oPQ5n+hFtw3QoXdRBoXvK2K+Qt1Ch7UDjo1JqHGN9ieHaWTUX+6ypWeYi8LcVknok9McVqGhdZAKHHwPL+98atEsn1Op+GQvxLyJ4c47RA6FXhKPBkHLZh5irg7QndVWKmwpgzFSS72GPtF+5xmpD+KPVFQ8meSu0qW2hf7UhW1oQsAIKxcjKoTfjWSYoI=
  on:
    tag: next
    tags: true
    repo: liquality/chainabstractionlayer
    branch: dev
