dist: trusty
sudo: required
language: node_js
addons:
  apt:
    packages:
      - docker-ce
node_js:
- 8
cache: npm
env:
  - DOCKER_COMPOSE_VERSION=1.25.2
before_install:
- sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
before_script:
- npm run bootstrap
- npm run lint
- npm run build
after_success: npm run coverage
