version: 2
jobs:
  lint_build_test:
    environment:
      BASH_ENV: /etc/profile
    docker:
      - image: mblackmblack/bitcoin-core-with-nvm:0.0.5
    working_directory: ~/chainabstractionlayer
    steps:
      - checkout
      - run:
          name: bitcoind
          command: bitcoind
      - run:
          name: npm install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build:prod
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_build_test
